#page title
page_title                                : Loophole\: Abstract Dash Adventure                                         # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                :                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            : https://play.google.com/store/apps/details?id=com.eighthbitlab.workaround                                          # Enter Google Play Store URL.
presskit_download_link                    : https://drive.google.com/file/d/1sWojW1fl-bU1mki-EELd_bP2aa5Jq3ms/view?usp=sharing                                       # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  : Loophole\: Abstract Dash Adventure                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 : Free                                          # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           : Dash, Lose, Retry! A challenging arcade game with an abstract geometric design

enable_smart_app_banner                   : false                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
your_name                                 : 8thBit Laboratory                               
your_link                                 : https://8tbl.github.io/                     
your_city                                 : Russia, Saint-Petersburg                                
email_address                             : 8thBitLab@gmail.com
facebook_username                         :                                           
instagram_username                        : 
twitter_username                          : 
github_username                           :
youtube_username                          :



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : SIMPLE AND UNIQUE CONTROL
    description                           : The gameplay is thought out specifically to make this game convenient to play on the phone, you only need one hand and a sharp reaction make a touch to change the direction of the particle. Press and hold to double particle speed.
    fontawesome_icon_name                 : star
    
  - title                                 : ABSTRACT DESIGN
    description                           : Beauty is in simplicity. The game is created in an abstract design and captivates with its simplicity of lines.
    fontawesome_icon_name                 : star


  - title                                 : SEVERAL CHAPTERS
    description                           : The adventure consists of three chapters with unique levels, each level differs from the other in its set of obstacles, speed, and rhythm. In the future, the number of chapters will increase and the levels will become more difficult :)
    fontawesome_icon_name                 : star
    
  - title                                 : THE PERFECTIONIST WAY
    description                           : This game contains a piece of a puzzle for you. Each of the levels can be completed in the optimal number of actions, the number of actions that are considered optimal for a given level is indicated in the upper left corner during the game, try to go through each of the levels along the reference path.
    fontawesome_icon_name                 : star
    
  - title                                 : SURVIVAL MODE
    description                           : The game has a survival mode or an endless game mode, where you will play as long as you can hold out!
    fontawesome_icon_name                 : star


  - title                                 : BEAUTIFUL ELECTRONIC MUSIC
    description                           : Music is specially selected for full immersion in the game. Quiet but persistent ambient will help you get into the rhythm of the game and get real pleasure from the process.
    fontawesome_icon_name                 : star


# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#000000"
cover_overlay_transparency                : 0.1

device_color                              : black                                     # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#070715"

link_color                                : "#3391ff"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#ffffff"
feature_text_color                        : "#cdcdcd"

feature_icons_foreground_color            : "#1d63ea"
feature_icons_background_color            : "#e6e6e6"

social_icons_foreground_color             : "#666666"
social_icons_background_color             : "#e6e6e6"

footer_text_color                         : "#cdcdcd"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
